const STORAGE = 'merk-of-duty.profile.v2';
const defaults = { name:'GUEST OPERATIVE', level:1, xp:0, wins:0, mode:'normal', quality:'hd', fov:90, aim:'TAP TO AIM', split:true, hud:true, sensitivity:1, minimap:100, hitmarkers:'ALL', layout:'STANDARD', audio:'HEADPHONES', vibration:true, fps60:true, hudEdit:false, operator:'Mara Vex', loadouts:{alpha:{primary:'Vanguard AR',secondary:'Sidearm 9',tactical:'Flash Charge',lethal:'Frag Device',perks:'Runner'},bravo:{primary:'Rook SMG',secondary:'Breaker Shotgun',tactical:'Signal Jammer',lethal:'Impact Charge',perks:'Deadeye'},charlie:{primary:'Longwatch Sniper',secondary:'Arc Pistol',tactical:'Smoke Capsule',lethal:'Proximity Mine',perks:'Field Medic'}}, sensX:1, sensY:1, lookDeadzone:0.08, moveDeadzone:0.12, adsSens:0.8, response:'STANDARD', fps:'60 FPS', graphics:'HIGH', fovScale:'VERTICAL', sprint:'AUTO SPRINT', slide:'TAP CROUCH', gyro:'OFF', filter:'STANDARD', motionBlur:false, depth:false, shadows:true, autoFire:false };
const load=()=>{try{return {...defaults,...JSON.parse(localStorage.getItem(STORAGE)||'{}')}}catch{return {...defaults}}};
const p=load(), $=q=>document.querySelector(q), hub=$('#merk-hub'), drawer=$('#merk-ops-drawer'), loading=$('#merk-loading');
const syncProfile=async()=>{try{await fetch('/api/profile',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({display_name:p.name,level:p.level,xp:p.xp,wins:p.wins,profile_json:p})})}catch{}};
const save=p=>{try{localStorage.setItem(STORAGE,JSON.stringify(p));syncProfile()}catch{}};
const loadProfile=async()=>{try{const r=await fetch('/api/profile');if(!r.ok)return;const d=await r.json();if(d?.profile_json){Object.assign(p,d.profile_json);localStorage.setItem(STORAGE,JSON.stringify(p));render()}}catch{}};
const modeNames={normal:'NORMAL MULTIPLAYER · AUTO MATCHMAKING',ranked:'RANKED · SKILL MATCHMAKING',hardcore:'HARDCORE · AUTO MATCHMAKING',zombies:'ZOMBIES · CO-OP MATCHMAKING'};
function render(){
  $('#merk-player-line').textContent=`${p.name} · LEVEL ${String(p.level).padStart(2,'0')}`; $('#merk-rank-badge').textContent=String(p.level).padStart(2,'0'); $('#merk-leader-score').textContent=`${p.wins} WINS`;
  $('#merk-rank-xp').textContent=`${p.xp.toLocaleString()} / 1,000 XP`; $('#merk-rank-progress')?.style.setProperty('width',`${Math.min(100,p.xp/10)}%`); $('#merk-rank-card').textContent=p.mode==='ranked'?'ROOKIE I // 0 RP':'READY // AUTO MATCHMAKING';
  $('#merk-quality').value=p.quality; $('#merk-fov').value=p.fov; $('#merk-fov-out').value=`${p.fov}°`; $('#merk-fov-out').textContent=`${p.fov}°`; $('#merk-aim').value=p.aim; $('#merk-split').checked=p.split; $('#merk-hud').checked=p.hud; $('#merk-hud-edit')?.setAttribute('checked',p.hudEdit?'':''); document.body.classList.toggle('hud-edit',p.hudEdit);
  $('#merk-sensitivity').value=p.sensitivity; $('#merk-sensitivity-out').textContent=`${Number(p.sensitivity).toFixed(1)}×`; for(const [id,key,fmt] of [['merk-sens-x','sensX',v=>Number(v).toFixed(2)+'×'],['merk-sens-y','sensY',v=>Number(v).toFixed(2)+'×'],['merk-look-deadzone','lookDeadzone',v=>Math.round(v*100)+'%'],['merk-move-deadzone','moveDeadzone',v=>Math.round(v*100)+'%'],['merk-ads-sens','adsSens',v=>Number(v).toFixed(2)+'×']]){$('#'+id)?.setAttribute('value',p[key]);$('#'+id+'-out')?.replaceChildren(fmt(p[key]))}; $('#merk-minimap').value=p.minimap; $('#merk-minimap-out').textContent=`${p.minimap}%`; $('#merk-hitmarkers').value=p.hitmarkers; $('#merk-layout').value=p.layout; $('#merk-audio').value=p.audio; $('#merk-vibration').checked=p.vibration; $('#merk-60fps').checked=p.fps60;
  document.querySelectorAll('.merk-mode').forEach(b=>b.classList.toggle('is-active',b.dataset.mode===p.mode));
}
function openDrawer(tab='play'){drawer.hidden=false;document.querySelectorAll('.merk-ops-nav button').forEach(b=>b.classList.toggle('is-active',b.dataset.merkTab===tab));document.querySelectorAll('[data-merk-view]').forEach(v=>v.classList.toggle('is-active',v.dataset.merkView===tab));$('#merk-drawer-title').textContent=tab==='play'?'OPERATIONS':tab.toUpperCase();}
function closeDrawer(){drawer.hidden=true}
function startLoading(){if(p.mode==='zombies'){const u=new URL(location.href);u.searchParams.set('mode','zombies');history.replaceState({},'',u)}closeDrawer();hub.hidden=true;loading.hidden=false;const bar=$('#merk-loading-bar'),pct=$('#merk-loading-percent'),cap=$('#merk-loading-caption');let n=0;const captions=['CONNECTING TO TACTICAL NETWORK','ALLOCATING FIRETEAM','SYNCING WEAPON DATA','MATCHMAKING OPERATIVES','LOADING COMBAT SHADERS'];const timer=setInterval(()=>{n=Math.min(96,n+Math.max(1,Math.round(Math.random()*5)));bar.style.width=`${n}%`;pct.textContent=`${n}%`;cap.textContent=captions[Math.min(captions.length-1,Math.floor(n/22))];if(n>=96)clearInterval(timer)},120);document.querySelector('#fe-load-game')?.click();setTimeout(()=>{bar.style.width='100%';pct.textContent='100%';cap.textContent='MATCH FOUND // DEPLOYING';document.querySelector('#blocker')?.click();setTimeout(()=>{loading.hidden=true},700)},5200)}
function bind(){
 document.querySelectorAll('.merk-ops-nav [data-merk-tab],.merk-ops-card[data-merk-tab]').forEach(b=>b.addEventListener('click',()=>openDrawer(b.dataset.merkTab)));
 $('#merk-hub-close')?.addEventListener('click',closeDrawer); document.querySelectorAll('.merk-mode').forEach(b=>b.addEventListener('click',()=>{p.mode=b.dataset.mode;save(p);render()})); $('#merk-deploy')?.addEventListener('click',startLoading); $('#merk-drawer-deploy')?.addEventListener('click',startLoading); $('#merk-ranked-start')?.addEventListener('click',()=>{p.mode='ranked';save(p);startLoading()});
 $('#merk-custom')?.addEventListener('click',()=>alert('Custom Games: choose rules and invite your fireteam. Public matchmaking never asks you to pick a map.')); $('#merk-signin')?.addEventListener('click',()=>{const name=prompt('Enter your operative name',p.name===defaults.name?'':p.name);if(name){p.name=name.toUpperCase().slice(0,18);save(p);render()}});
 const settingIds={ 'merk-sens-x':['sensX',Number], 'merk-sens-y':['sensY',Number], 'merk-look-deadzone':['lookDeadzone',Number], 'merk-move-deadzone':['moveDeadzone',Number], 'merk-ads-sens':['adsSens',Number], 'merk-response':['response',String], 'merk-fps':['fps',String], 'merk-graphics':['graphics',String], 'merk-fov-scale':['fovScale',String], 'merk-sprint':['sprint',String], 'merk-slide':['slide',String], 'merk-gyro':['gyro',String], 'merk-filter':['filter',String] }; Object.entries(settingIds).forEach(([id,[key,fn]])=>{const el=$('#'+id); if(el){el.value=p[key]; el.addEventListener(el.type==='range'?'input':'change',e=>{p[key]=fn(e.target.value);save(p);render()})}}); ['motionBlur','depth','shadows','autoFire'].forEach(key=>{const id='merk-'+({'motionBlur':'motion-blur','depth':'depth','shadows':'shadows','autoFire':'auto-fire'}[key]);const el=$('#'+id);if(el){el.checked=p[key];el.addEventListener('change',e=>{p[key]=e.target.checked;save(p)})}});
  const bindVal=(id,key,fn=String)=>$('#'+id)?.addEventListener('change',e=>{p[key]=fn(e.target.value);save(p);render()}); bindVal('merk-quality','quality'); bindVal('merk-aim','aim'); bindVal('merk-hitmarkers','hitmarkers'); bindVal('merk-layout','layout'); bindVal('merk-audio','audio'); bindVal('merk-sensitivity','sensitivity',Number); bindVal('merk-minimap','minimap',Number);
 $('#merk-fov')?.addEventListener('input',e=>{p.fov=Number(e.target.value);save(p);render()}); $('#merk-split')?.addEventListener('change',e=>{p.split=e.target.checked;save(p)}); $('#merk-hud')?.addEventListener('change',e=>{p.hud=e.target.checked;save(p);document.body.classList.toggle('merk-hud-hidden',!p.hud)}); $('#merk-hud-edit')?.addEventListener('change',e=>{p.hudEdit=e.target.checked;save(p);document.body.classList.toggle('hud-edit',p.hudEdit)}); $('#merk-vibration')?.addEventListener('change',e=>{p.vibration=e.target.checked;save(p)}); document.querySelectorAll('[data-operator]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-operator]').forEach(x=>x.classList.remove('is-active'));b.classList.add('is-active');p.operator=b.dataset.operator;save(p);$('#merk-operator-selected').textContent=`SELECTED // ${p.operator.toUpperCase()}`})); document.querySelectorAll('[data-loadout]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-loadout]').forEach(x=>x.classList.remove('is-active'));b.classList.add('is-active');const l=p.loadouts[b.dataset.loadout];if(l){for(const [id,key] of [['class-primary','primary'],['class-secondary','secondary'],['class-tactical','tactical'],['class-lethal','lethal'],['class-perks','perks']])$('#'+id).value=l[key]}})); async function auth(kind){const email=$('#merk-auth-email')?.value.trim(),password=$('#merk-auth-password')?.value,name=$('#merk-auth-name')?.value.trim();const status=$('#merk-auth-status');if(!email||!password||(kind==='signup'&&!name)){status.textContent='EMAIL, PASSWORD AND IN-GAME NAME REQUIRED';return}status.textContent='CONNECTING…';try{const r=await fetch('/api/auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:kind,email,password,displayName:name})});const d=await r.json();if(!r.ok)throw Error(d.error||'AUTH FAILED');p.name=(d.displayName||name||p.name).replace(/^@/,'');save(p);render();loadProfile();status.textContent=`SIGNED IN // @${p.name}`;}catch(e){status.textContent=e.message.toUpperCase()}} $('#merk-signup')?.addEventListener('click',()=>auth('signup')); $('#merk-login')?.addEventListener('click',()=>auth('login')); document.querySelectorAll('[data-attachment]').forEach(b=>b.addEventListener('click',()=>b.classList.toggle('is-active')));
$('#class-save')?.addEventListener('click',()=>{const tab=document.querySelector('[data-loadout].is-active')?.dataset.loadout||'alpha';p.loadouts[tab]={primary:$('#class-primary').value,secondary:$('#class-secondary').value,tactical:$('#class-tactical').value,lethal:$('#class-lethal').value,perks:$('#class-perks').value};save(p);alert(`${tab.toUpperCase()} LOADOUT SAVED`)}); $('#merk-60fps')?.addEventListener('change',e=>{p.fps60=e.target.checked;save(p)});
}
bind(); render(); hub.hidden=false; openDrawer('play'); setInterval(()=>{const el=$('#merk-clock');if(el)el.textContent=new Date().toISOString().slice(11,19)+' ZULU'},1000); window.merkOfDuty={profile:p,openHub:()=>{hub.hidden=false},closeHub:()=>{hub.hidden=true}};

loadProfile();
