export const RANK_TIERS = Object.freeze([
  ...['ROOKIE','VETERAN','ELITE','PRO'].flatMap(t => [1,2,3,4,5].map(d => ({name:`${t} ${['I','II','III','IV','V'][d-1]}`, tier:t, division:d, floor:0}))),
  {name:'MASTER',tier:'MASTER',division:0,floor:2000},{name:'GRANDMASTER',tier:'GRANDMASTER',division:0,floor:2600},{name:'LEGENDARY',tier:'LEGENDARY',division:0,floor:3200}
]);
export const SEASON = Object.freeze({number:1,name:'BLACKOUT PROTOCOL',start:'2026-09-01',end:'2026-10-31',resetRp:0});
export function rankForRP(rp=0){const n=Math.max(0,Number(rp)||0);let i=0;for(let j=0;j<RANK_TIERS.length;j++){const floor= j<20 ? j*100 : RANK_TIERS[j].floor;if(n>=floor)i=j;}const next=i<RANK_TIERS.length-1?(i<19?(i+1)*100: RANK_TIERS[i+1].floor):null;const floor=i<20?i*100:RANK_TIERS[i].floor;return {...RANK_TIERS[i],floor,next,progress:next?Math.min(1,(n-floor)/(next-floor)):1};}
export function calculateRP({won=false,kills=0,deaths=0,assists=0,objective=0,damage=0,teamContribution=0,mmr=1000,opponentMmr=1000,currentRp=0}={}){const perf=Math.max(-1,Math.min(1,((kills*2+assists+objective/100+damage/500+teamContribution/100)-(deaths*1.5))/30));const result=won?25:-22;const skill=Math.max(-10,Math.min(10,Math.round((opponentMmr-mmr)/100)));const performance=Math.round(perf*12);const rp=Math.max(-35,Math.min(40,result+skill+performance));return {rp,performanceRating:Math.round(50+perf*50),breakdown:{result,skill,performance}};}
export function updateMMR({mmr=1000,won=false,performanceRating=50,opponentMmr=1000}={}){const expected=1/(1+10**((opponentMmr-mmr)/400));const actual=won?1:0;return Math.max(100,Math.round(mmr+24*(actual-expected)+(performanceRating-50)*0.15));}
export function matchmakingBand({mmr=1000,partySize=1,recentPerformance=50}={}){const width=Math.min(350,120+partySize*35+Math.abs(recentPerformance-50)*2);return {min:Math.max(0,mmr-width),max:mmr+width,partySize};}
export function validateMatch(input={}){const fields=['kills','deaths','assists','objective','damage'];for(const f of fields)if(!Number.isFinite(Number(input[f]))||Number(input[f])<0)return {ok:false,error:`invalid_${f}`};if(Number(input.kills)>100||Number(input.deaths)>100||Number(input.assists)>100||Number(input.damage)>100000)return {ok:false,error:'impossible_statistics'};if(!input.matchId||!input.playerId)return {ok:false,error:'missing_identity'};return {ok:true};}
