import * as THREE from 'three';

export const ZOMBIES_CONFIG = Object.freeze({
  intermission: 4, spawnInterval: .32, maxActive: 28, spawnProtection: 650,
  baseCount: 6, countPerRound: 3, health: 110, healthScale: .16, speed: 74,
  speedScale: .025, damage: 12, attackRange: 52, attackCooldown: .85,
  headshotMultiplier: 2.2, reviveTime: 3, maxHealth: 100, maxArmor: 50,
  killPoints: 100, headshotPoints: 50, damagePoints: 10, revivePoints: 250,
  specialEvery: 5, capRoundHealth: 1800,
});
const V={normal:{health:1,speed:1,damage:1,scale:1},fast:{health:.55,speed:1.65,damage:.75,scale:.8},heavy:{health:3.5,speed:.5,damage:2.5,scale:1.35},ranged:{health:1.4,speed:.8,damage:1.1,scale:1},boss:{health:12,speed:.72,damage:4,scale:1.8}};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
export class DifficultyManager { constructor(config=ZOMBIES_CONFIG){this.c=config} forRound(round){const special=round%this.c.specialEvery===0;return {round,special,count:Math.min(this.c.maxActive*2,this.c.baseCount+(round-1)*this.c.countPerRound),health:Math.min(this.c.capRoundHealth,this.c.health*(1+(round-1)*this.c.healthScale)),speed:this.c.speed*(1+(round-1)*this.c.speedScale),damage:this.c.damage*(1+Math.min(.8,(round-1)*.035)),spawnInterval:Math.max(.12,this.c.spawnInterval/(1+(round-1)*.035))}}}
export class ScoreSystem { constructor(){this.points=0;this.kills=0;this.headshots=0;this.damage=0;this.revives=0} damageDone(n){this.damage+=n;this.points+=Math.floor(n/10)*10} kill(head=false){this.kills++;if(head)this.headshots++;this.points+=ZOMBIES_CONFIG.killPoints+(head?ZOMBIES_CONFIG.headshotPoints:0)} revive(){this.revives++;this.points+=ZOMBIES_CONFIG.revivePoints} snapshot(){return {points:this.points,kills:this.kills,headshots:this.headshots,damage:this.damage,revives:this.revives}}}
export class PlayerState { constructor(health,config=ZOMBIES_CONFIG){this.config=config;this.health=typeof health==='number'?health:(health?.health??config.maxHealth);this.armor=config.maxArmor;this.downed=false;this.reviveProgress=0;this.dead=false} damage(amount){if(this.dead)return{amount:0};let a=Math.max(0,amount);const absorb=Math.min(this.armor,a*.55);this.armor-=absorb;a-=absorb;const applied=Math.min(this.health,a);this.health-=applied;if(this.health<=0){if(!this.downed){this.downed=true;this.health=1}else this.dead=true}return{amount:applied+absorb,downed:this.downed,dead:this.dead}} revive(){if(!this.downed||this.dead)return false;this.downed=false;this.health=Math.round(this.config.maxHealth*.35);this.armor=0;return true} update(dt){if(this.downed&&!this.dead)this.reviveProgress+=dt;}}
class ZombieAI { constructor(root,manager){this.root=root;this.manager=manager;this.hitboxes=[];this.reset()} reset(){this.dead=false;this.state='idle';this.health=1;this.maxHealth=1;this.speed=0;this.damage=0;this.attackTimer=0;this.stagger=0;this.variant='normal';this.target=null;this.path=[];this.pathIndex=0;this.nextPath=0} spawn(position,variant,stats){this.reset();this.root.visible=true;this.root.position.copy(position);this.variant=variant;const v=V[variant];this.maxHealth=stats.health*v.health;this.health=this.maxHealth;this.speed=stats.speed*v.speed;this.damage=stats.damage*v.damage;this.root.scale.setScalar(v.scale);this.state='chase'} takeDamage(amount,hit){if(this.dead)return{damage:0,killed:false,headshot:false};const head=hit?.object?.userData?.region==='head';const damage=amount*(head?this.manager.config.headshotMultiplier:1);this.health-=damage;this.manager.score.damageDone(damage);this.stagger=Math.min(.2,this.stagger+.05);if(this.health<=0){this.dead=true;this.state='death';this.root.visible=false;this.manager.score.kill(head);this.manager.onKill?.(this,head)}return{damage,killed:this.dead,headshot:head,region:head?'head':'torso'}} update(dt){if(this.dead)return;this.attackTimer=Math.max(0,this.attackTimer-dt);this.stagger=Math.max(0,this.stagger-dt);const target=this.manager.nearestTarget(this.root.position);if(!target)return;this.target=target;const p=target.position||target;const dx=p.x-this.root.position.x,dz=p.z-this.root.position.z,dist=Math.hypot(dx,dz);if(dist<=(this.variant==='ranged'?260:this.manager.config.attackRange)){this.state='attack';if(this.attackTimer<=0){this.attackTimer=this.manager.config.attackCooldown*(this.variant==='fast'?.65:1);this.manager.damagePlayer(this.damage,this)}}else{this.state=this.stagger?'stagger':'chase';const inv=1/Math.max(dist,.001);this.root.position.x+=dx*inv*this.speed*dt;this.root.position.z+=dz*inv*this.speed*dt;this.root.rotation.y=Math.atan2(-dx,-dz)}}}
export class ZombieSpawner { constructor(manager,hints,player){this.manager=manager;this.player=player;this.zones=(hints?.spawns||hints?.pathnodes||[]).map(x=>new THREE.Vector3(...(x.position||x)));this.fallback=[new THREE.Vector3(900,0,900),new THREE.Vector3(-900,0,900),new THREE.Vector3(900,0,-900),new THREE.Vector3(-900,0,-900)]} pick(){const all=this.zones.length?this.zones:this.fallback;const candidates=all.filter(p=>p.distanceTo(this.player.position)>this.manager.config.spawnProtection);return (candidates.length?candidates:all)[Math.floor(Math.random()*(candidates.length||all.length))].clone()}}
export class RoundManager { constructor(manager){this.manager=manager;this.round=0;this.phase='waiting';this.remainingToSpawn=0;this.intermission=0;this.spawnTimer=0} start(){this.round=0;this.nextRound()} nextRound(){this.round++;this.stats=this.manager.difficulty.forRound(this.round);this.remainingToSpawn=this.stats.count;this.phase='spawning';this.spawnTimer=0;this.manager.onRound?.(this.round,this.stats)} update(dt){if(this.phase==='spawning'){this.spawnTimer-=dt;if(this.remainingToSpawn>0&&this.spawnTimer<=0&&this.manager.activeCount<this.manager.config.maxActive){this.manager.spawnOne(this.stats);this.remainingToSpawn--;this.spawnTimer=this.stats.spawnInterval}if(this.remainingToSpawn<=0)this.phase='combat'}else if(this.phase==='combat'&&this.manager.activeCount===0){this.phase='intermission';this.intermission=this.manager.config.intermission;this.manager.onIntermission?.(this.intermission)}else if(this.phase==='intermission'){this.intermission-=dt;if(this.intermission<=0)this.nextRound()}}}
export class ZombieManager { constructor({scene,player,playerHealth,navigation,hints,config=ZOMBIES_CONFIG,onRound,onKill,onGameOver,onHud}={}){this.scene=scene;this.player=player;this.playerState=new PlayerState(playerHealth,config);this.navigation=navigation;this.config=config;this.onRound=onRound;this.onKill=onKill;this.onGameOver=onGameOver;this.onHud=onHud;this.difficulty=new DifficultyManager(config);this.score=new ScoreSystem();this.spawner=new ZombieSpawner(this,hints,player);this.rounds=new RoundManager(this);this.pool=[];this.active=[];for(let i=0;i<config.maxActive*2;i++)this.pool.push(this.makeZombie());this.rounds.start()} makeZombie(){const root=new THREE.Group();const body=new THREE.Mesh(new THREE.CapsuleGeometry(15,35,4,8),new THREE.MeshStandardMaterial({color:0x6b8790,roughness:.9}));body.position.y=32;body.userData.enemyHit=null;const head=new THREE.Mesh(new THREE.SphereGeometry(12,8,6),body.material);head.position.y=68;head.userData.enemyHit=null;head.userData.region='head';root.add(body,head);this.scene.add(root);const z=new ZombieAI(root,this);z.hitboxes=[body,head];body.userData.enemyHit={enemy:z,region:'torso',multiplier:1};head.userData.enemyHit={enemy:z,region:'head',multiplier:1};root.visible=false;return z} get activeCount(){return this.active.filter(z=>!z.dead).length} get hitTargets(){return this.active.filter(z=>!z.dead).flatMap(z=>z.hitboxes)} get actors(){return this.active.filter(z=>!z.dead).map(enemy=>({enemy,position:enemy.root.position.clone().add(new THREE.Vector3(0,40,0))}))} spawnOne(stats){const z=this.pool.find(x=>x.dead||!x.root.visible);if(!z)return;const types=stats.special?(this.rounds.round%10===0?'boss':this.rounds.round%7===0?'ranged':this.rounds.round%2?'fast':'heavy'):'normal';z.spawn(this.spawner.pick(),types,stats);this.active.push(z)} nearestTarget(){if(this.playerState.dead)return null;return {position:this.player.position}} damagePlayer(amount,source){const result=this.playerState.damage(amount);if(result.dead){this.onGameOver?.(this.score.snapshot());this.rounds.phase='gameover'}this.onHud?.(this.hudState());return result} handlePlayerHit(hit,baseDamage=34){const d=hit?.object?.userData?.enemyHit;if(!d?.enemy)return null;return d.enemy.takeDamage(typeof baseDamage==='function'?baseDamage(d.region,hit.distance||0):baseDamage,hit)} update(dt){if(this.rounds.phase==='gameover')return;this.playerState.update(dt);this.rounds.update(dt);for(const z of this.active)z.update(dt);this.onHud?.(this.hudState())} hudState(){return {round:this.rounds.round,phase:this.rounds.phase,remaining:this.rounds.stats?this.rounds.remainingToSpawn+this.activeCount:0,active:this.activeCount,points:this.score.points,kills:this.score.kills,downed:this.playerState.downed,gameOver:this.playerState.dead}}}
